packages:
  Then:
    url: https://github.com/devxoul/Then
    from: 2.7.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.0.1
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    from: 5.1.0
  RxCocoa:
    url: https://github.com/ReactiveX/RxSwift
    from: 5.1.0
