name: {ProjectName}
include:
  - package.yml
options:
   deploymentTarget:
     iOS: 15.0
   createIntermediateGroups: true
   bundleIdPrefix: com.milkyo
targets:
  {ProjectName}:
    platform: iOS
    type: application
    info:
      path: {ProjectName}/Supporting Files/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
              UIApplicationSupportsMultipleScenes: false
              UISceneConfigurations:
                UIWindowSceneSessionRoleApplication:
                  - UISceneConfigurationName: Default Configuration
                    UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
    settings:
      base:
       SWIFT_VERSION: 5.5
       TARGETED_DEVICE_FAMILY: 1,2
    sources:
      - {ProjectName}/Sources
      - {ProjectName}/Supporting Files
    dependencies:
      - package: Then
      - package: SnapKit
      - package: RxSwift
      - package: RxCocoa
